packages:
- ./

resolver: ghc-8.2
compiler: ghc-8.2
system-ghc: true

extra-deps:
  - QuickCheck-2.9.2
  - hspec-2.4.3
  - HUnit-1.6.0.0
  - call-stack-0.1.0
  - hspec-core-2.4.3
  - hspec-discover-2.4.3
  - hspec-expectations-0.8.2
  - random-1.1
  - tf-random-0.5
  - ansi-terminal-0.6.2.3
  - async-2.1.1.1
  - primitive-0.6.2.0
  - quickcheck-io-0.1.4
  - setenv-0.1.1.3
  - stm-2.4.4.1
  - socket-0.8.0.1

# For benchmarking only:  
  - criterion-1.2.0.0
  - Glob-0.8.0
  - aeson-1.2.1.0
  - ansi-wl-pprint-0.6.7.3
  - base-compat-0.9.3
  - cassava-0.5.0.0
  - code-page-0.1.3
  - exceptions-0.8.3
  - js-flot-0.8.3
  - js-jquery-3.2.1
  - microstache-1
  - mtl-2.2.1
  - mwc-random-0.13.6.0
  - optparse-applicative-0.14.0.0
  - parsec-3.1.11
  - statistics-0.14.0.2
  - text-1.2.2.2
  - transformers-compat-0.5.1.4
  - vector-0.12.0.1
  - vector-algorithms-0.7.0.1
  - Only-0.1
  - attoparsec-0.13.1.0
  - base-orphans-0.6
  - bytestring-builder-0.10.8.1.0
  - dlist-0.8.0.2
  - erf-2.0.0.0
  - hashable-1.2.6.0
  - math-functions-0.2.1.0
  - monad-par-0.3.4.8
  - scientific-0.3.4.15
  - tagged-0.8.5
  - time-locale-compat-0.1.1.3
  - unordered-containers-0.2.8.0
  - uuid-types-1.0.3
  - vector-binary-instances-0.2.3.5
  - vector-th-unbox-0.2.1.6
  - abstract-deque-0.3
  - abstract-par-0.3.3
  - integer-logarithms-1.0.1
  - monad-par-extras-0.3.3
  - old-locale-1.0.0.7
  - parallel-3.2.1.1
  - cereal-0.5.4.0

allow-newer: true

docker:
  enable: true
  image: tweag/linear-types:0.1.5
